### PR TITLE
poetry package manager

### PR DESCRIPTION
**Pull request by amazingvince**
Pre-commit is run by using `poetry check`. 
Virtual-env is set up by running `poetry shell`
You can also just run something in the virtual-env with `poetry run`

### CODE REVIEW

**Comment by ankrgyl** [comment]
With this change, can we remove some or all of `setup.py`?

**Comment by amazingvince** [comment]
Yes, please double check I grabbed everything out of it first :)

**Comment by ankrgyl** [comment]
I'll verify this a bit later and follow up!

**Comment by ankrgyl** [comment]
I'm a little confused about how to use it. I downloaded a fresh repo, and ran the following commands:

```
$ poetry check
$ poetry shell
$ poetry install
# This took ~3 minutes to run and created a poetry.lock file, which I believe is supposed to be committed

$ docqa --help
# docqa: command not found
```

**Comment by amazingvince** [comment]
https://python-poetry.org/docs/#osx--linux--bashonwindows-install-instructions

**Comment by ankrgyl** [comment]
To clarify -- I was able to install poetry just fine. I just think we need to make it as seamless as the current experience, which is that someone can run exactly one command (`make develop`, or another command that we specify) which will (a) notify the user of any dependencies they need to install (e.g. poetry), (b) setup the virtualenv + dependencies, and (c) allow them to run the `docqa` command in their path.

**Comment by amazingvince** [comment]
So poetry will build the virtual env for them but they only need to have that installed if they want to build from sources. We should build a wheel file and have people pip install a release to use the package.

If you have poetry on your machine you can simply `poetry run docqa scan ... `

**Comment by ankrgyl** [comment]
We already do build a wheel file and publish it (see the `build` and `publish` targets in the Makefile). We should definitely make sure these work with poetry -- I just hadn't gotten far enough yet to do that. I think we need to solve the lock file issue (among others) that I raised above first.

Is there a way to setup poetry so that `docqa` is part of `PATH` and you do not need to run it through the wrapper? We often `pip install -e` these packages among other repos (e.g. while co-developing with https://github.com/impira/impira-python), so do not want to break that workflow.

**Comment by amazingvince** [comment]
Just updated the code in the colab to use poetry install which will install all dependencies into current python env. Also adding lockfile not required but speeds up dependency resolution.

**Comment by ankrgyl** [comment]
I pulled this down and observed that a file named `docqa` is indeed in my path, but when I run it, I see the following:

```
(docqa-8lUQQKmq-py3.10) ankur-m1:~/tmp/docqa ankur$ docqa --help
Traceback (most recent call last):
  File "/Users/ankur/Library/Caches/pypoetry/virtualenvs/docqa-8lUQQKmq-py3.10/bin/docqa", line 5, in <module>
    __main__()
TypeError: 'module' object is not callable
```

I suspect you need to update the entrypoint to be `__main__.main`

**Comment by amazingvince** [comment]
Closing this. Not feeling it is providing benefit.

**Pull request closed without merging**
